packages:
  - "packages/*"

allowBuilds:
  '@google/genai': set this to true or false
  esbuild: true
  koffi: set this to true or false
  protobufjs: set this to true or false

minimumReleaseAge: 10080
